[colors]
# Regular colors
background = "#fcfaf2" # bg,      shironeri
black = "#fcfaf2"      # bg,      shironeri
blue = "#005caf"       # blue,    ruri
cyan = "#3a8fb7"       # cyan,    chigusa
foreground = "#0f2540" # fg,      kon
green = "#268785"      # green,   seiheki
magenta = "#e03c8a"    # magenta, tsutsuji
red = "#cb1b45"        # red,     kurenai
white = "#0f2540"      # fg,      kon
yellow = "#96632e"     # yellow,  chojicha

# Cursor
cursor = "#0f2540"    # fg, kon
vi-cursor = "#0f2540" # fg, kon

# Navigation
tabs = "#bdc0ba"                   # bg0,   shironezumi
tabs-foreground = "#434343"        # fg0,   keshizumi
tabs-active = "#fcfaf2"            # bg,    shironeri
tabs-active-foreground = "#0f2540" # fg,    kon
tabs-active-highlight = "#7db9de"  # cyan0, wasurenagusa
bar = "#7db9de"                    # cyan0, wasurenagusa

# Search
search-match-background = "#7db9de"         # cyan0, wasurenagusa
search-match-foreground = "#0f2540"         # fg,    kon
search-focused-match-background = "#0f2540" # fg,    kon
search-focused-match-foreground = "#fcfaf2" # bg,    shironeri

# Selection
selection-background = "#bdc0ba" # bg0, shironezumi
selection-foreground = "#0f2540" # fg,  kon

# Dim colors
dim-black = "#fcfaf2"      # bg,      shironeri
dim-blue = "#005caf"       # blue,    ruri
dim-cyan = "#3a8fb7"       # cyan,    chigusa
dim-foreground = "#434343" # fg0,     keshizumi
dim-green = "#268785"      # green,   seiheki
dim-magenta = "#e03c8a"    # magenta, tsutsuji
dim-red = "#cb1b45"        # red,     kurenai
dim-white = "#434343"      # fg0,     keshizumi
dim-yellow = "#96632e"     # yellow,  chojicha

# Light colors
light-black = "#bdc0ba"      # bg0,      shironezumi
light-blue = "#2ea9df"       # blue0,    tsuyukusa
light-cyan = "#7db9de"       # cyan0,    wasurenagusa
light-foreground = "#0f2540" # fg,       kon
light-green = "#66bab7"      # green0,   mizuasagi
light-magenta = "#f596aa"    # magenta0, momo
light-red = "#db4d6d"        # red0,     nakabeni
light-white = "#0f2540"      # fg,       kon
light-yellow = "#f7c242"     # yellow0,  hanaba
