[colors]
# Regular colors
background = "#08192d" # bg,      kachi
black = "#08192d"      # bg,      kachi
blue = "#2ea9df"       # blue,    tsuyukusa
cyan = "#7db9de"       # cyan,    wasurenagusa
foreground = "#bdc0ba" # fg,      shironezumi
green = "#66bab7"      # green,   mizuasagi
magenta = "#f596aa"    # magenta, momo
red = "#db4d6d"        # red,     nakabeni
white = "#bdc0ba"      # fg,      shironezumi
yellow = "#f7c242"     # yellow,  hanaba

# Cursor
cursor = "#bdc0ba"    # fg, shironezumi
vi-cursor = "#bdc0ba" # fg, shironezumi

# Navigation
tabs = "#0f2540"                   # bg0,   kon
tabs-foreground = "#91989f"        # fg0,   ginnezumi
tabs-active = "#08192d"            # bg,    kachi
tabs-active-foreground = "#bdc0ba" # fg,    shironezumi
tabs-active-highlight = "#3a8fb7"  # cyan0, chigusa
bar = "#3a8fb7"                    # cyan0, chigusa

# Search
search-match-background = "#3a8fb7"         # cyan0, chigusa
search-match-foreground = "#bdc0ba"         # fg,    shironezumi
search-focused-match-background = "#bdc0ba" # fg,    shironezumi
search-focused-match-foreground = "#08192d" # bg,    kachi

# Selection
selection-background = "#0f2540" # bg0, kon
selection-foreground = "#bdc0ba" # fg,  shironezumi

# Dim colors
dim-black = "#08192d"      # bg,       kachi
dim-blue = "#005caf"       # blue0,    ruri
dim-cyan = "#3a8fb7"       # cyan0,    chigusa
dim-foreground = "#91989f" # fg0,      ginnezumi
dim-green = "#268785"      # green0,   seiheki
dim-magenta = "#e03c8a"    # magenta0, tsutsuji
dim-red = "#cb1b45"        # red0,     kurenai
dim-white = "#91989f"      # fg0,      ginnezumi
dim-yellow = "#96632e"     # yellow0,  chojicha

# Light colors
light-black = "#0f2540"      # bg0,     kon
light-blue = "#2ea9df"       # blue,    tsuyukusa
light-cyan = "#7db9de"       # cyan,    wasurenagusa
light-foreground = "#bdc0ba" # fg,      shironezumi
light-green = "#66bab7"      # green,   mizuasagi
light-magenta = "#f596aa"    # magenta, momo
light-red = "#db4d6d"        # red,     nakabeni
light-white = "#bdc0ba"      # fg,      shironezumi
light-yellow = "#f7c242"     # yellow,  hanaba
